import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContractCountsSnapshot",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("upload_date", models.DateField()),
                ("igk", models.CharField(max_length=10)),
                ("cfo", models.CharField(max_length=10)),
                ("year_col", models.CharField(max_length=5)),
                ("concluded_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Снимок количества договоров",
                "verbose_name_plural": "Снимки количества договоров",
                "db_table": "contract_counts_snapshot",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ContractsHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("hash", models.BinaryField()),
                ("old_status", models.CharField(max_length=500, null=True)),
                ("new_status", models.CharField(max_length=500, null=True)),
                ("update_date", models.DateField(null=True)),
                ("upload_date", models.DateField(null=True)),
                ("old_plan", models.FloatField(null=True)),
                ("new_plan", models.FloatField(null=True)),
                ("old_fact", models.FloatField(null=True)),
                ("new_fact", models.FloatField(null=True)),
                ("plan_changed_date", models.DateField(null=True)),
                ("fact_changed_date", models.DateField(null=True)),
            ],
            options={
                "verbose_name": "Изменение договора",
                "verbose_name_plural": "Изменения договоров",
                "db_table": "contracts_history",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="IgkStatData",
            fields=[
                ("pp_id", models.AutoField(primary_key=True, serialize=False)),
                ("igk", models.CharField(max_length=500, null=True)),
                ("c_agent", models.CharField(max_length=500, null=True)),
                ("cfo", models.CharField(max_length=500, null=True)),
                ("contract", models.CharField(max_length=500, null=True)),
                ("status", models.CharField(max_length=500, null=True)),
                ("payment_type", models.CharField(max_length=500, null=True)),
                ("item", models.CharField(max_length=500, null=True)),
                (
                    "order",
                    models.CharField(db_column='"order"', max_length=500, null=True),
                ),
                ("plan", models.FloatField(null=True)),
                ("fact", models.FloatField(null=True)),
                ("tolerance", models.FloatField(null=True)),
                ("stage", models.CharField(max_length=250, null=True)),
                ("y25", models.BooleanField(null=True)),
                ("y26", models.BooleanField(null=True)),
                ("y27", models.BooleanField(null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("plan_date", models.CharField(max_length=50, null=True)),
                ("c_date", models.CharField(max_length=256, null=True)),
                ("crc32_hash", models.BigIntegerField()),
            ],
            options={
                "verbose_name": "Позиция договора",
                "verbose_name_plural": "Позиции договоров",
                "db_table": "igk_stat_data",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="NsiCfo",
            fields=[
                ("cfo_id", models.AutoField(primary_key=True, serialize=False)),
                ("cfo", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "ЦФО",
                "verbose_name_plural": "ЦФО",
                "db_table": "nsi_cfo",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="NsiIgk",
            fields=[
                ("igk_id", models.AutoField(primary_key=True, serialize=False)),
                ("igk", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "ИГК",
                "verbose_name_plural": "ИГК",
                "db_table": "nsi_igk",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="StagingExcel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("igk", models.TextField(null=True)),
                ("kontragent", models.TextField(null=True)),
                ("cfo", models.TextField(null=True)),
                ("dogovor", models.TextField(null=True)),
                ("sostoyanie", models.TextField(null=True)),
                ("tip_platezha", models.TextField(null=True)),
                ("predmet", models.TextField(null=True)),
                ("zakaz", models.TextField(null=True)),
                ("plan", models.TextField(null=True)),
                ("fakt", models.TextField(null=True)),
                ("tol", models.TextField(null=True)),
                ("etap_grafika", models.TextField(null=True)),
                ("dataplan", models.TextField(null=True)),
                ("sozdan", models.TextField(null=True)),
                ("god_igk", models.TextField(null=True)),
            ],
            options={
                "verbose_name": "Строка импорта",
                "verbose_name_plural": "Строки импорта",
                "db_table": "staging_excel",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="StagingZnpExcel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("igk", models.TextField(null=True)),
                ("znp_igk", models.TextField(null=True)),
                ("znp_payment_type", models.CharField(null=True)),
                ("c_agent", models.TextField(null=True)),
                ("contract", models.TextField(null=True)),
                ("stage", models.TextField(null=True)),
                ("plan_doc", models.TextField(null=True)),
                ("payment_purpose", models.TextField(null=True)),
                ("plan_payment_date", models.TextField(null=True)),
                ("fact_payment_date", models.TextField(null=True)),
                ("plan_sum", models.FloatField(null=True)),
                ("fact_sum", models.FloatField(null=True)),
                ("crc32_hash", models.BigIntegerField()),
            ],
            options={
                "verbose_name": "Строка импорта ЗнП",
                "verbose_name_plural": "Строка импорта ЗнП",
                "db_table": "staging_znp_excel",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="StagingZnpSAPExcel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("igk", models.CharField(null=True)),
                ("cfo", models.CharField(max_length=4)),
                ("c_agent", models.CharField()),
                ("reg_num", models.CharField(null=True)),
                ("items", models.CharField(null=True)),
                ("vv_sum", models.FloatField(null=True)),
                ("bank_name", models.CharField(null=True)),
                ("c_type", models.CharField()),
                ("stage_e", models.DateField(null=True)),
                ("stage_f", models.DateField(null=True)),
                ("payment_possible", models.DateField(null=True)),
                ("normalize_doc_num", models.CharField(null=True)),
            ],
            options={
                "verbose_name": "Строка импорта ЗнП(САП)",
                "verbose_name_plural": "Строка импорта ЗнП(САП)",
                "db_table": "staging_znp_sap_excel",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ZnpDataSAP",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("igk", models.CharField(null=True)),
                ("cfo", models.CharField(max_length=4, null=True)),
                ("c_agent", models.CharField()),
                ("reg_num", models.CharField(null=True)),
                ("items", models.CharField(null=True)),
                ("vv_sum", models.FloatField(null=True)),
                ("bank_name", models.CharField(null=True)),
                ("stage_e", models.DateField(null=True)),
                ("stage_f", models.DateField(null=True)),
                ("payment_possible", models.DateField(null=True)),
                ("normalize_doc_num", models.CharField(null=True)),
            ],
            options={
                "verbose_name": "Заявки на платёж(САП)",
                "verbose_name_plural": "Заявка на платёж(САП)",
                "db_table": "znp_data_sap",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ZnpData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("crc32_hash", models.BigIntegerField(null=True)),
                ("stage", models.CharField(max_length=250, null=True)),
                ("plan_doc", models.CharField(null=True)),
                ("payment_purpose", models.CharField(null=True)),
                ("plan_payment_date", models.DateField(null=True)),
                ("fact_payment_date", models.DateField(null=True)),
                ("plan_sum", models.FloatField(null=True)),
                ("fact_sum", models.FloatField(null=True)),
                ("znp_igk", models.TextField(null=True)),
                ("znp_payment_type", models.CharField(null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reports.igkstatdata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявки на платёж",
                "verbose_name_plural": "Заявка на платёж",
                "db_table": "znp_data",
                "managed": True,
            },
        ),
    ]
