# Generated by Django 6.0.2 on 2026-03-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractsHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hash', models.BinaryField()),
                ('old_status', models.CharField(max_length=500, null=True)),
                ('new_status', models.CharField(max_length=500, null=True)),
                ('update_date', models.DateField(null=True)),
                ('upload_date', models.DateField(null=True)),
                ('old_plan', models.FloatField(null=True)),
                ('new_plan', models.FloatField(null=True)),
                ('old_fact', models.FloatField(null=True)),
                ('new_fact', models.FloatField(null=True)),
                ('plan_changed_date', models.DateField(null=True)),
                ('fact_changed_date', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'Изменение договора',
                'db_table': 'contracts_history',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IgkStatData',
            fields=[
                ('pp_id', models.AutoField(primary_key=True, serialize=False)),
                ('igk', models.CharField(max_length=500, null=True)),
                ('c_agent', models.CharField(max_length=500, null=True)),
                ('cfo', models.CharField(max_length=500, null=True)),
                ('contract', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(max_length=500, null=True)),
                ('payment_type', models.CharField(max_length=500, null=True)),
                ('item', models.CharField(max_length=500, null=True)),
                ('order', models.CharField(db_column='"order"', max_length=500, null=True)),
                ('plan', models.FloatField(null=True)),
                ('fact', models.FloatField(null=True)),
                ('tolerance', models.FloatField(null=True)),
                ('stage', models.CharField(max_length=250, null=True)),
                ('y25', models.BooleanField(null=True)),
                ('y26', models.BooleanField(null=True)),
                ('y27', models.BooleanField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('plan_date', models.CharField(max_length=50, null=True)),
                ('c_date', models.CharField(max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Позиция договора',
                'db_table': 'igk_stat_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NsiCfo',
            fields=[
                ('cfo_id', models.AutoField(primary_key=True, serialize=False)),
                ('cfo', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'ЦФО',
                'db_table': 'nsi_cfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NsiIgk',
            fields=[
                ('igk_id', models.AutoField(primary_key=True, serialize=False)),
                ('igk', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'ИГК',
                'db_table': 'nsi_igk',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StagingExcel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('igk', models.TextField(null=True)),
                ('kontragent', models.TextField(null=True)),
                ('cfo', models.TextField(null=True)),
                ('dogovor', models.TextField(null=True)),
                ('sostoyanie', models.TextField(null=True)),
                ('tip_platezha', models.TextField(null=True)),
                ('predmet', models.TextField(null=True)),
                ('zakaz', models.TextField(null=True)),
                ('plan', models.TextField(null=True)),
                ('fakt', models.TextField(null=True)),
                ('tol', models.TextField(null=True)),
                ('etap_grafika', models.TextField(null=True)),
                ('dataplan', models.TextField(null=True)),
                ('sozdan', models.TextField(null=True)),
                ('god_igk', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Строка импорта',
                'db_table': 'staging_excel',
                'managed': True,
            },
        ),
    ]
