# Generated by Django 6.0.2 on 2026-03-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractCountsSnapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_date', models.DateField()),
                ('igk', models.CharField(max_length=10)),
                ('cfo', models.CharField(max_length=10)),
                ('year_col', models.CharField(max_length=5)),
                ('concluded_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Снимок количества договоров',
                'verbose_name_plural': 'Снимки количества договоров',
                'db_table': 'contract_counts_snapshot',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='contractshistory',
            options={'managed': True, 'verbose_name': 'Изменение договора', 'verbose_name_plural': 'Изменения договоров'},
        ),
        migrations.AlterModelOptions(
            name='igkstatdata',
            options={'managed': True, 'verbose_name': 'Позиция договора', 'verbose_name_plural': 'Позиции договоров'},
        ),
        migrations.AlterModelOptions(
            name='nsicfo',
            options={'managed': True, 'verbose_name': 'ЦФО', 'verbose_name_plural': 'ЦФО'},
        ),
        migrations.AlterModelOptions(
            name='nsiigk',
            options={'managed': True, 'verbose_name': 'ИГК', 'verbose_name_plural': 'ИГК'},
        ),
        migrations.AlterModelOptions(
            name='stagingexcel',
            options={'managed': True, 'verbose_name': 'Строка импорта', 'verbose_name_plural': 'Строки импорта'},
        ),
    ]
