# Generated by Django 6.0.2 on 2026-08-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_contract_sum"),
    ]

    operations = [
        migrations.AddField(
            model_name="stagingexcel",
            name="summa_dogovora",
            field=models.TextField(null=True),
        ),
    ]
