# Generated by Django 6.0.2 on 2026-08-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0007_drop_staging_sozdan"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField()),
            ],
        ),
    ]
