# Generated by Django 6.0.2 on 2026-08-05 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0008_testtable"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestTable",
        ),
    ]
