# Generated by Django 6.0.2 on 2026-08-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0009_delete_testtable"),
    ]

    operations = [
        migrations.AddField(
            model_name="igkstatdata",
            name="remainder",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="stagingexcel",
            name="ostatok",
            field=models.TextField(null=True),
        ),
    ]
