# Generated by Django 6.0.2 on 2026-08-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0010_igkstatdata_remainder_stagingexcel_ostatok"),
    ]

    operations = [
        migrations.AlterField(
            model_name="igkstatdata",
            name="remainder",
            field=models.FloatField(null=True),
        ),
    ]
