# Generated by Django 6.0.2 on 2026-08-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0011_alter_igkstatdata_remainder"),
    ]

    operations = [
        migrations.AddField(
            model_name="stagingznpexcel",
            name="znp_date",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="znpdata",
            name="znp_date",
            field=models.DateField(null=True),
        ),
    ]
