# Generated by Django 6.0.2 on 2026-08-13 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_stagingznpexcel_znp_date_znpdata_znp_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NsiCfo',
        ),
        migrations.RemoveField(
            model_name='igkstatdata',
            name='is_deleted',
        ),
    ]
