# Generated by Django 6.0.2 on 2026-08-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0014_pgcrypto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Access",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("access_dashboard", "Раздел: Договорная работа"),
                    ("access_znp", "Раздел: ЗнП (ФЗД)"),
                    ("access_znp_sap", "Раздел: ЗнП (SAP)"),
                    ("access_kdr", "Раздел: КДР по годам"),
                    ("access_igk", "Раздел: ИГК по годам"),
                    ("access_history", "Раздел: История изменений"),
                    ("access_dupes", "Раздел: Дубликаты"),
                    ("access_export", "Раздел: Отчёты в Excel"),
                    ("access_upload", "Раздел: Загрузка данных"),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
