# Generated by Django 6.0.2 on 2026-08-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractsAppeared',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_date', models.DateField()),
                ('kind', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=20)),
                ('igk', models.CharField(max_length=500, null=True)),
                ('cfo', models.CharField(max_length=500, null=True)),
                ('c_agent', models.CharField(max_length=500, null=True)),
                ('contract', models.CharField(max_length=500, null=True)),
                ('item', models.CharField(max_length=500, null=True)),
                ('order_num', models.CharField(max_length=500, null=True)),
                ('stage', models.CharField(max_length=500, null=True)),
                ('plan_date', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(max_length=500, null=True)),
                ('plan', models.FloatField(null=True)),
                ('contract_sum', models.FloatField(null=True)),
            ],
        ),
    ]
