# Generated by Django 6.0.2 on 2026-08-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_contractsappeared'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractsappeared',
            options={'managed': True, 'verbose_name': 'Появившийся договор', 'verbose_name_plural': 'Появившиеся договоры'},
        ),
        migrations.AddIndex(
            model_name='contractsappeared',
            index=models.Index(fields=['upload_date', 'kind'], name='contracts_a_upload__365998_idx'),
        ),
        migrations.AlterModelTable(
            name='contractsappeared',
            table='contracts_appeared',
        ),
    ]
