# Generated by Django 6.0.2 on 2026-08-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_alter_contractsappeared_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_key', models.CharField(max_length=50, unique=True)),
                ('event_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Системные события',
                'verbose_name_plural': 'Системные события',
                'db_table': 'system_events',
                'managed': True,
            },
        ),
    ]
