# Generated by Django 6.0.2 on 2026-08-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_systemevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagingznpsapexcel',
            name='init_payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='znpdatasap',
            name='init_payment_date',
            field=models.DateField(null=True),
        ),
    ]
