# Generated by Django 6.0.3 on 2026-09-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sync_error',
            field=models.TextField(blank=True, verbose_name='Ошибка последней синхронизации'),
        ),
    ]
