# Generated by Django 6.0.3 on 2026-09-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_profile_last_synced_at_profile_sync_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='api_key',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='API ключ'),
        ),
    ]
