# Generated by Django 6.0.2 on 2026-09-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0022_alter_profile_api_key"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "managed": True,
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
            },
        ),
        migrations.AlterModelOptions(
            name="stagingznpsapexcel",
            options={
                "managed": True,
                "verbose_name": "Строка импорта ЗнП(САП)",
                "verbose_name_plural": "Строки импорта ЗнП(САП)",
            },
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="znp_payment_type",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="bank_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="c_agent",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="c_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="igk",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="items",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="normalize_doc_num",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="reg_num",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="znpdata",
            name="payment_purpose",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="znpdata",
            name="plan_doc",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="znpdata",
            name="znp_payment_type",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="bank_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="c_agent",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="igk",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="items",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="normalize_doc_num",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="reg_num",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name="profile",
            table="reports_profile",
        ),
    ]
