# Generated by Django 6.0.2 on 2026-09-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_alter_profile_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagingznpsapexcel',
            name='cfo',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='znpdatasap',
            name='cfo',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
