# Generated by Django 6.0.2 on 2026-09-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_alter_stagingznpsapexcel_cfo_alter_znpdatasap_cfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagingznpsapexcel',
            name='cfo',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='znpdatasap',
            name='cfo',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
