# Generated by Django 6.0.2 on 2026-09-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0023_alter_profile_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stagingznpsapexcel",
            options={
                "managed": True,
                "verbose_name": "Строка импорта ЗнП (SAP)",
                "verbose_name_plural": "Строки импорта ЗнП (SAP)",
            },
        ),
        migrations.AlterModelOptions(
            name="systemevent",
            options={
                "managed": True,
                "verbose_name": "Системное событие",
                "verbose_name_plural": "Системные события",
            },
        ),
        migrations.AlterModelOptions(
            name="znpdatasap",
            options={
                "managed": True,
                "verbose_name": "Заявка на платёж (SAP)",
                "verbose_name_plural": "Заявки на платёж (SAP)",
            },
        ),
        migrations.AlterField(
            model_name="contractcountssnapshot",
            name="igk",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="contractsappeared",
            name="c_agent",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="contractsappeared",
            name="cfo",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="contractsappeared",
            name="contract",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="contractsappeared",
            name="contract_sum",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractsappeared",
            name="igk",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="contractsappeared",
            name="item",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="contractsappeared",
            name="order_num",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="contractsappeared",
            name="plan",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractsappeared",
            name="plan_date",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="contractsappeared",
            name="stage",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="contractsappeared",
            name="status",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="contractshistory",
            name="fact_changed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractshistory",
            name="new_contract_sum",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractshistory",
            name="new_fact",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractshistory",
            name="new_plan",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractshistory",
            name="new_status",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="contractshistory",
            name="old_contract_sum",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractshistory",
            name="old_fact",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractshistory",
            name="old_plan",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractshistory",
            name="old_status",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="contractshistory",
            name="plan_changed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractshistory",
            name="update_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractshistory",
            name="upload_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="c_agent",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="c_date",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="cfo",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="contract",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="contract_sum",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="fact",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="igk",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="item",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="order",
            field=models.CharField(
                blank=True, db_column="order", max_length=500, null=True
            ),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="payment_type",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="plan",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="plan_date",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="remainder",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="stage",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="status",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="tolerance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="y25",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="y26",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="y27",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="cfo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="dataplan",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="dogovor",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="etap_grafika",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="fakt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="god_igk",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="igk",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="kontragent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="ostatok",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="plan",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="predmet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="sostoyanie",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="summa_dogovora",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="tip_platezha",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="tol",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="zakaz",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="c_agent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="contract",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="fact_payment_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="fact_sum",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="igk",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="payment_purpose",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="plan_doc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="plan_payment_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="plan_sum",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="stage",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="znp_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="znp_igk",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="znp_payment_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="znp_status",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="bank_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="c_agent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="c_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="cfo",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="igk",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="init_payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="items",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="normalize_doc_num",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="payment_possible",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="reg_num",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="stage_e",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="stage_f",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="vv_sum",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="znpdata",
            name="crc32_hash",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="znpdata",
            name="fact_payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="znpdata",
            name="fact_sum",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="znpdata",
            name="payment_purpose",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="znpdata",
            name="plan_doc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="znpdata",
            name="plan_payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="znpdata",
            name="plan_sum",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="znpdata",
            name="stage",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="znpdata",
            name="znp_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="znpdata",
            name="znp_igk",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="znpdata",
            name="znp_payment_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="znpdata",
            name="znp_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="bank_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="c_agent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="cfo",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="igk",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="init_payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="items",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="normalize_doc_num",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="payment_possible",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="reg_num",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="stage_e",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="stage_f",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="vv_sum",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
