# Generated by Django 6.0.2 on 2026-09-08 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0024_alter_stagingznpsapexcel_cfo_alter_znpdatasap_cfo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nsiigk",
            options={
                "managed": True,
                "verbose_name": "Справочник ИГК",
                "verbose_name_plural": "Справочник ИГК",
            },
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
            },
        ),
        migrations.AlterModelOptions(
            name="stagingexcel",
            options={
                "managed": True,
                "verbose_name": "Строка импорта договоров",
                "verbose_name_plural": "Строки импорта договоров",
            },
        ),
        migrations.AlterModelOptions(
            name="stagingznpexcel",
            options={
                "managed": True,
                "verbose_name": "Строка импорта ЗнП (ФЗД)",
                "verbose_name_plural": "Строки импорта ЗнП (ФЗД)",
            },
        ),
        migrations.AlterModelOptions(
            name="stagingznpsapexcel",
            options={
                "managed": True,
                "verbose_name": "Строка импорта ЗнП (SAP)",
                "verbose_name_plural": "Строки импорта ЗнП (SAP)",
            },
        ),
        migrations.AlterModelOptions(
            name="systemevent",
            options={
                "managed": True,
                "verbose_name": "Системное событие",
                "verbose_name_plural": "Системные события",
            },
        ),
        migrations.AlterModelOptions(
            name="znpdata",
            options={
                "managed": True,
                "verbose_name": "Заявка на платёж (ФЗД)",
                "verbose_name_plural": "Заявки на платёж (ФЗД)",
            },
        ),
        migrations.AlterModelOptions(
            name="znpdatasap",
            options={
                "managed": True,
                "verbose_name": "Заявка на платёж (SAP)",
                "verbose_name_plural": "Заявки на платёж (SAP)",
            },
        ),
        migrations.RenameIndex(
            model_name="contractsappeared",
            new_name="idx_appeared_date_kind",
            old_name="contracts_a_upload__365998_idx",
        ),
        migrations.RenameIndex(
            model_name="contractshistory",
            new_name="idx_history_hash",
            old_name="contracts_h_hash_23adb6_idx",
        ),
        migrations.RenameIndex(
            model_name="igkstatdata",
            new_name="idx_igk_crc32",
            old_name="igk_stat_da_crc32_h_1965c4_idx",
        ),
        migrations.RenameIndex(
            model_name="igkstatdata",
            new_name="idx_igk_code",
            old_name="igk_stat_da_igk_46cfe1_idx",
        ),
        migrations.RenameIndex(
            model_name="igkstatdata",
            new_name="idx_igk_cfo",
            old_name="igk_stat_da_cfo_2cf4c7_idx",
        ),
        migrations.RenameIndex(
            model_name="igkstatdata",
            new_name="idx_igk_status",
            old_name="igk_stat_da_status_99097f_idx",
        ),
        migrations.RenameIndex(
            model_name="igkstatdata",
            new_name="idx_igk_payment",
            old_name="igk_stat_da_payment_441c09_idx",
        ),
        migrations.RenameIndex(
            model_name="znpdata",
            new_name="idx_znp_crc32",
            old_name="znp_data_crc32_h_2b86ce_idx",
        ),
        migrations.RenameIndex(
            model_name="znpdatasap",
            new_name="idx_sap_cfo",
            old_name="znp_data_sa_cfo_03ed7d_idx",
        ),
        migrations.RenameIndex(
            model_name="znpdatasap",
            new_name="idx_sap_igk",
            old_name="znp_data_sa_igk_d6552e_idx",
        ),
        migrations.AlterField(
            model_name="contractcountssnapshot",
            name="cfo",
            field=models.CharField(max_length=500, verbose_name="ЦФО"),
        ),
        migrations.AlterField(
            model_name="contractcountssnapshot",
            name="concluded_count",
            field=models.IntegerField(default=0, verbose_name="Количество заключённых"),
        ),
        migrations.AlterField(
            model_name="contractcountssnapshot",
            name="igk",
            field=models.CharField(max_length=10, verbose_name="Код ИГК"),
        ),
        migrations.AlterField(
            model_name="contractcountssnapshot",
            name="upload_date",
            field=models.DateField(verbose_name="Дата загрузки (снимка)"),
        ),
        migrations.AlterField(
            model_name="contractcountssnapshot",
            name="year_col",
            field=models.CharField(
                max_length=5, verbose_name="Колонка года (y25, y26...)"
            ),
        ),
        migrations.AlterField(
            model_name="contractsappeared",
            name="c_agent",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Контрагент"
            ),
        ),
        migrations.AlterField(
            model_name="contractsappeared",
            name="cfo",
            field=models.CharField(max_length=500, null=True, verbose_name="ЦФО"),
        ),
        migrations.AlterField(
            model_name="contractsappeared",
            name="contract",
            field=models.CharField(max_length=500, null=True, verbose_name="Договор"),
        ),
        migrations.AlterField(
            model_name="contractsappeared",
            name="contract_sum",
            field=models.FloatField(null=True, verbose_name="Сумма договора"),
        ),
        migrations.AlterField(
            model_name="contractsappeared",
            name="igk",
            field=models.CharField(max_length=500, null=True, verbose_name="ИГК"),
        ),
        migrations.AlterField(
            model_name="contractsappeared",
            name="item",
            field=models.CharField(max_length=500, null=True, verbose_name="Предмет"),
        ),
        migrations.AlterField(
            model_name="contractsappeared",
            name="kind",
            field=models.CharField(
                max_length=20, verbose_name="Тип появления (новый/изменил статус)"
            ),
        ),
        migrations.AlterField(
            model_name="contractsappeared",
            name="order_num",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Номер заказа"
            ),
        ),
        migrations.AlterField(
            model_name="contractsappeared",
            name="plan",
            field=models.FloatField(null=True, verbose_name="План"),
        ),
        migrations.AlterField(
            model_name="contractsappeared",
            name="plan_date",
            field=models.CharField(
                max_length=20, null=True, verbose_name="Плановая дата"
            ),
        ),
        migrations.AlterField(
            model_name="contractsappeared",
            name="reason",
            field=models.CharField(max_length=20, verbose_name="Причина"),
        ),
        migrations.AlterField(
            model_name="contractsappeared",
            name="stage",
            field=models.CharField(max_length=500, null=True, verbose_name="Этап"),
        ),
        migrations.AlterField(
            model_name="contractsappeared",
            name="status",
            field=models.CharField(max_length=500, null=True, verbose_name="Статус"),
        ),
        migrations.AlterField(
            model_name="contractsappeared",
            name="upload_date",
            field=models.DateField(verbose_name="Дата загрузки"),
        ),
        migrations.AlterField(
            model_name="contractshistory",
            name="fact_changed_date",
            field=models.DateField(null=True, verbose_name="Дата изменения факта"),
        ),
        migrations.AlterField(
            model_name="contractshistory",
            name="hash",
            field=models.BinaryField(verbose_name="MD5 хеш позиции"),
        ),
        migrations.AlterField(
            model_name="contractshistory",
            name="new_contract_sum",
            field=models.FloatField(null=True, verbose_name="Новая сумма договора"),
        ),
        migrations.AlterField(
            model_name="contractshistory",
            name="new_fact",
            field=models.FloatField(null=True, verbose_name="Новый факт"),
        ),
        migrations.AlterField(
            model_name="contractshistory",
            name="new_plan",
            field=models.FloatField(null=True, verbose_name="Новый план"),
        ),
        migrations.AlterField(
            model_name="contractshistory",
            name="new_status",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Новый статус"
            ),
        ),
        migrations.AlterField(
            model_name="contractshistory",
            name="old_contract_sum",
            field=models.FloatField(null=True, verbose_name="Старая сумма договора"),
        ),
        migrations.AlterField(
            model_name="contractshistory",
            name="old_fact",
            field=models.FloatField(null=True, verbose_name="Старый факт"),
        ),
        migrations.AlterField(
            model_name="contractshistory",
            name="old_plan",
            field=models.FloatField(null=True, verbose_name="Старый план"),
        ),
        migrations.AlterField(
            model_name="contractshistory",
            name="old_status",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Старый статус"
            ),
        ),
        migrations.AlterField(
            model_name="contractshistory",
            name="plan_changed_date",
            field=models.DateField(null=True, verbose_name="Дата изменения плана"),
        ),
        migrations.AlterField(
            model_name="contractshistory",
            name="update_date",
            field=models.DateField(null=True, verbose_name="Дата изменения в файле"),
        ),
        migrations.AlterField(
            model_name="contractshistory",
            name="upload_date",
            field=models.DateField(null=True, verbose_name="Дата загрузки в систему"),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="c_agent",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Контрагент"
            ),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="c_date",
            field=models.CharField(
                max_length=256, null=True, verbose_name="Дата заключения (строка)"
            ),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="cfo",
            field=models.CharField(max_length=500, null=True, verbose_name="ЦФО"),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="contract",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Номер договора"
            ),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="contract_sum",
            field=models.FloatField(null=True, verbose_name="Сумма всего договора"),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="crc32_hash",
            field=models.BigIntegerField(verbose_name="CRC32 хеш для привязки"),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="fact",
            field=models.FloatField(null=True, verbose_name="Фактическая сумма"),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="igk",
            field=models.CharField(max_length=500, null=True, verbose_name="Код ИГК"),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="item",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Предмет договора"
            ),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="order",
            field=models.CharField(
                db_column="order",
                max_length=500,
                null=True,
                verbose_name="Номер заказа",
            ),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="payment_type",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Тип платежа"
            ),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="plan",
            field=models.FloatField(null=True, verbose_name="Плановая сумма"),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="plan_date",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Плановая дата (строка)"
            ),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="pp_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="Внутренний ID"
            ),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="remainder",
            field=models.FloatField(null=True, verbose_name="Остаток"),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="stage",
            field=models.CharField(
                max_length=250, null=True, verbose_name="Этап графика"
            ),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="status",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Статус договора"
            ),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="tolerance",
            field=models.FloatField(null=True, verbose_name="Допуск (%)"),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="y25",
            field=models.BooleanField(null=True, verbose_name="Флаг 2025 года"),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="y26",
            field=models.BooleanField(null=True, verbose_name="Флаг 2026 года"),
        ),
        migrations.AlterField(
            model_name="igkstatdata",
            name="y27",
            field=models.BooleanField(null=True, verbose_name="Флаг 2027 года"),
        ),
        migrations.AlterField(
            model_name="nsiigk",
            name="igk",
            field=models.CharField(max_length=50, unique=True, verbose_name="Код ИГК"),
        ),
        migrations.AlterField(
            model_name="nsiigk",
            name="igk_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID записи"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="cfo",
            field=models.TextField(null=True, verbose_name="ЦФО"),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="dataplan",
            field=models.TextField(null=True, verbose_name="Дата план"),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="dogovor",
            field=models.TextField(null=True, verbose_name="Договор"),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="etap_grafika",
            field=models.TextField(null=True, verbose_name="Этап графика"),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="fakt",
            field=models.TextField(null=True, verbose_name="Факт"),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="god_igk",
            field=models.TextField(null=True, verbose_name="Год ИГК"),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="igk",
            field=models.TextField(null=True, verbose_name="ИГК"),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="kontragent",
            field=models.TextField(null=True, verbose_name="Контрагент"),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="ostatok",
            field=models.TextField(null=True, verbose_name="Остаток"),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="plan",
            field=models.TextField(null=True, verbose_name="План"),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="predmet",
            field=models.TextField(null=True, verbose_name="Предмет"),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="sostoyanie",
            field=models.TextField(null=True, verbose_name="Состояние"),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="summa_dogovora",
            field=models.TextField(null=True, verbose_name="Сумма договора"),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="tip_platezha",
            field=models.TextField(null=True, verbose_name="Тип платежа"),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="tol",
            field=models.TextField(null=True, verbose_name="Допуск"),
        ),
        migrations.AlterField(
            model_name="stagingexcel",
            name="zakaz",
            field=models.TextField(null=True, verbose_name="Заказ"),
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="c_agent",
            field=models.TextField(null=True, verbose_name="Контрагент"),
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="contract",
            field=models.TextField(null=True, verbose_name="Договор"),
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="crc32_hash",
            field=models.BigIntegerField(verbose_name="CRC32 хеш для привязки"),
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="fact_payment_date",
            field=models.TextField(null=True, verbose_name="Фактическая дата"),
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="fact_sum",
            field=models.FloatField(null=True, verbose_name="Фактическая сумма"),
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="igk",
            field=models.TextField(null=True, verbose_name="ИГК"),
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="payment_purpose",
            field=models.TextField(null=True, verbose_name="Назначение платежа"),
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="plan_doc",
            field=models.TextField(null=True, verbose_name="Плановый документ"),
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="plan_payment_date",
            field=models.TextField(null=True, verbose_name="Плановая дата"),
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="plan_sum",
            field=models.FloatField(null=True, verbose_name="Плановая сумма"),
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="stage",
            field=models.TextField(null=True, verbose_name="Этап"),
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="znp_date",
            field=models.TextField(null=True, verbose_name="Дата заявки"),
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="znp_igk",
            field=models.TextField(null=True, verbose_name="ИГК заявки"),
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="znp_payment_type",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Тип платежа заявки"
            ),
        ),
        migrations.AlterField(
            model_name="stagingznpexcel",
            name="znp_status",
            field=models.TextField(null=True, verbose_name="Статус заявки"),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="bank_name",
            field=models.CharField(max_length=500, null=True, verbose_name="Банк"),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="c_agent",
            field=models.CharField(max_length=500, verbose_name="Контрагент"),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="c_type",
            field=models.CharField(max_length=50, verbose_name="Тип"),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="cfo",
            field=models.CharField(max_length=4, verbose_name="ЦФО"),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="igk",
            field=models.CharField(max_length=500, null=True, verbose_name="ИГК"),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="init_payment_date",
            field=models.DateField(null=True, verbose_name="Изначальная дата платежа"),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="items",
            field=models.CharField(max_length=500, null=True, verbose_name="Предметы"),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="normalize_doc_num",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Нормализованный номер"
            ),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="payment_possible",
            field=models.DateField(null=True, verbose_name="Возможная дата платежа"),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="reg_num",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Рег. номер"
            ),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="stage_e",
            field=models.DateField(null=True, verbose_name="Этап E"),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="stage_f",
            field=models.DateField(null=True, verbose_name="Этап F"),
        ),
        migrations.AlterField(
            model_name="stagingznpsapexcel",
            name="vv_sum",
            field=models.FloatField(null=True, verbose_name="Сумма ВВ"),
        ),
        migrations.AlterField(
            model_name="systemevent",
            name="event_key",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Ключ события"
            ),
        ),
        migrations.AlterField(
            model_name="systemevent",
            name="event_time",
            field=models.DateTimeField(verbose_name="Время события"),
        ),
        migrations.AlterField(
            model_name="znpdata",
            name="crc32_hash",
            field=models.BigIntegerField(null=True, verbose_name="CRC32 хеш"),
        ),
        migrations.AlterField(
            model_name="znpdata",
            name="fact_payment_date",
            field=models.DateField(null=True, verbose_name="Фактическая дата платежа"),
        ),
        migrations.AlterField(
            model_name="znpdata",
            name="fact_sum",
            field=models.FloatField(null=True, verbose_name="Фактическая сумма"),
        ),
        migrations.AlterField(
            model_name="znpdata",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reports.igkstatdata",
                verbose_name="Родительская позиция договора",
            ),
        ),
        migrations.AlterField(
            model_name="znpdata",
            name="payment_purpose",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Назначение платежа"
            ),
        ),
        migrations.AlterField(
            model_name="znpdata",
            name="plan_doc",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Плановый документ"
            ),
        ),
        migrations.AlterField(
            model_name="znpdata",
            name="plan_payment_date",
            field=models.DateField(null=True, verbose_name="Плановая дата платежа"),
        ),
        migrations.AlterField(
            model_name="znpdata",
            name="plan_sum",
            field=models.FloatField(null=True, verbose_name="Плановая сумма"),
        ),
        migrations.AlterField(
            model_name="znpdata",
            name="stage",
            field=models.CharField(max_length=250, null=True, verbose_name="Этап"),
        ),
        migrations.AlterField(
            model_name="znpdata",
            name="znp_date",
            field=models.DateField(null=True, verbose_name="Дата заявки"),
        ),
        migrations.AlterField(
            model_name="znpdata",
            name="znp_igk",
            field=models.TextField(null=True, verbose_name="ИГК заявки"),
        ),
        migrations.AlterField(
            model_name="znpdata",
            name="znp_payment_type",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Тип платежа"
            ),
        ),
        migrations.AlterField(
            model_name="znpdata",
            name="znp_status",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Статус заявки"
            ),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="bank_name",
            field=models.CharField(max_length=500, null=True, verbose_name="Банк"),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="c_agent",
            field=models.CharField(max_length=500, verbose_name="Контрагент"),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="cfo",
            field=models.CharField(max_length=4, null=True, verbose_name="ЦФО"),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="igk",
            field=models.CharField(max_length=500, null=True, verbose_name="ИГК"),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="init_payment_date",
            field=models.DateField(null=True, verbose_name="Изначальная дата платежа"),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="items",
            field=models.CharField(max_length=500, null=True, verbose_name="Предметы"),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="normalize_doc_num",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Нормализованный номер"
            ),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="payment_possible",
            field=models.DateField(null=True, verbose_name="Возможная дата платежа"),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="reg_num",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Рег. номер"
            ),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="stage_e",
            field=models.DateField(null=True, verbose_name="Этап E"),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="stage_f",
            field=models.DateField(null=True, verbose_name="Этап F"),
        ),
        migrations.AlterField(
            model_name="znpdatasap",
            name="vv_sum",
            field=models.FloatField(null=True, verbose_name="Сумма ВВ"),
        ),
    ]
