# Generated by Django 6.0.2 on 2026-09-22 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0025_alter_nsiigk_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'default_permissions': (), 'managed': False, 'permissions': [('access_dashboard', 'Раздел: Договорная работа'), ('access_znp', 'Раздел: ЗнП (ФЗД)'), ('access_znp_sap', 'Раздел: ЗнП (SAP)'), ('access_kdr', 'Раздел: КДР по годам'), ('access_igk', 'Раздел: ИГК по годам'), ('access_history', 'Раздел: История изменений'), ('access_dupes', 'Раздел: Дубликаты'), ('access_export', 'Раздел: Отчёты в Excel'), ('access_upload', 'Раздел: Загрузка данных'), ('access_goz_report', 'Раздел: Анализ ГОЗ')]},
        ),
    ]
