# Generated by Django 6.1.1 on 2026-09-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0026_alter_access_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractcountssnapshot',
            options={'verbose_name': 'Снимок количества договоров', 'verbose_name_plural': 'Снимки количества договоров'},
        ),
        migrations.AlterModelOptions(
            name='contractsappeared',
            options={'verbose_name': 'Появившийся договор', 'verbose_name_plural': 'Появившиеся договоры'},
        ),
        migrations.AlterModelOptions(
            name='contractshistory',
            options={'verbose_name': 'Изменение договора', 'verbose_name_plural': 'Изменения договоров'},
        ),
        migrations.AlterModelOptions(
            name='igkstatdata',
            options={'verbose_name': 'Позиция договора', 'verbose_name_plural': 'Позиции договоров'},
        ),
        migrations.AlterModelOptions(
            name='nsiigk',
            options={'verbose_name': 'Справочник ИГК', 'verbose_name_plural': 'Справочник ИГК'},
        ),
        migrations.AlterModelOptions(
            name='stagingexcel',
            options={'verbose_name': 'Строка импорта договоров', 'verbose_name_plural': 'Строки импорта договоров'},
        ),
        migrations.AlterModelOptions(
            name='stagingznpexcel',
            options={'verbose_name': 'Строка импорта ЗнП (ФЗД)', 'verbose_name_plural': 'Строки импорта ЗнП (ФЗД)'},
        ),
        migrations.AlterModelOptions(
            name='stagingznpsapexcel',
            options={'verbose_name': 'Строка импорта ЗнП (SAP)', 'verbose_name_plural': 'Строки импорта ЗнП (SAP)'},
        ),
        migrations.AlterModelOptions(
            name='systemevent',
            options={'verbose_name': 'Системное событие', 'verbose_name_plural': 'Системные события'},
        ),
        migrations.AlterModelOptions(
            name='znpdata',
            options={'verbose_name': 'Заявка на платёж (ФЗД)', 'verbose_name_plural': 'Заявки на платёж (ФЗД)'},
        ),
        migrations.AlterModelOptions(
            name='znpdatasap',
            options={'verbose_name': 'Заявка на платёж (SAP)', 'verbose_name_plural': 'Заявки на платёж (SAP)'},
        ),
        migrations.AlterField(
            model_name='contractsappeared',
            name='contract_sum',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Сумма договора'),
        ),
        migrations.AlterField(
            model_name='contractsappeared',
            name='kind',
            field=models.CharField(max_length=20, verbose_name='Тип появления'),
        ),
        migrations.AlterField(
            model_name='contractsappeared',
            name='plan',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='План'),
        ),
        migrations.AlterField(
            model_name='contractshistory',
            name='new_contract_sum',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Новая сумма договора'),
        ),
        migrations.AlterField(
            model_name='contractshistory',
            name='new_fact',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Новый факт'),
        ),
        migrations.AlterField(
            model_name='contractshistory',
            name='new_plan',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Новый план'),
        ),
        migrations.AlterField(
            model_name='contractshistory',
            name='old_contract_sum',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Старая сумма договора'),
        ),
        migrations.AlterField(
            model_name='contractshistory',
            name='old_fact',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Старый факт'),
        ),
        migrations.AlterField(
            model_name='contractshistory',
            name='old_plan',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Старый план'),
        ),
        migrations.AlterField(
            model_name='igkstatdata',
            name='contract_sum',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Сумма всего договора'),
        ),
        migrations.AlterField(
            model_name='igkstatdata',
            name='fact',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Фактическая сумма'),
        ),
        migrations.AlterField(
            model_name='igkstatdata',
            name='plan',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Плановая сумма'),
        ),
        migrations.AlterField(
            model_name='igkstatdata',
            name='remainder',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='igkstatdata',
            name='tolerance',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Допуск (%)'),
        ),
        migrations.AlterField(
            model_name='znpdata',
            name='fact_sum',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Фактическая сумма'),
        ),
        migrations.AlterField(
            model_name='znpdata',
            name='plan_sum',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Плановая сумма'),
        ),
        migrations.AlterField(
            model_name='znpdatasap',
            name='vv_sum',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Сумма ВВ'),
        ),
        migrations.AddIndex(
            model_name='znpdata',
            index=models.Index(fields=['parent_id'], name='idx_znp_parent'),
        ),
    ]
