# Generated by Django 6.1.1 on 2026-09-23 17:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0027_alter_contractcountssnapshot_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GozContractVat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igk', models.CharField(max_length=10, unique=True, verbose_name='ГК')),
                ('vat_rate', models.DecimalField(decimal_places=1, default=Decimal('20.0'), max_digits=4, verbose_name='Ставка НДС, %')),
            ],
            options={
                'verbose_name': 'ГК (ставка НДС)',
                'verbose_name_plural': 'Анализ ГОЗ: справочник ставок НДС',
                'db_table': 'goz_contract_vat',
                'ordering': ['igk'],
            },
        ),
    ]
