# Generated by Django 6.0.2 on 2026-09-24 03:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0028_gozcontractvat'),
    ]

    operations = [
        migrations.AddField(
            model_name='gozcontractvat',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Изделие'),
        ),
        migrations.AddField(
            model_name='gozcontractvat',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='gozcontractvat',
            name='vat_rate',
            field=models.DecimalField(decimal_places=1, default=Decimal('22.0'), max_digits=4, verbose_name='Ставка НДС, %'),
        ),
    ]
