# Generated by Django 6.0.2 on 2026-09-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0029_gozcontractvat_product_gozcontractvat_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='znpdatasap',
            name='stage_c',
            field=models.DateField(null=True, verbose_name='Этап C'),
        ),
    ]
