# Generated by Django 6.0.2 on 2026-09-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0030_znpdatasap_stage_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagingznpsapexcel',
            name='stage_с',
            field=models.DateField(null=True, verbose_name='Этап С'),
        ),
    ]
