# Generated by Django 6.0.2 on 2026-09-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0031_stagingznpsapexcel_stage_с'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stagingznpsapexcel',
            old_name='stage_с',
            new_name='stage_c',
        ),
    ]
