# Generated by Django 6.0.2 on 2026-09-29 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0032_rename_stage_с_stagingznpsapexcel_stage_c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagingznpsapexcel',
            name='init_payment_date',
        ),
        migrations.RemoveField(
            model_name='znpdatasap',
            name='init_payment_date',
        ),
    ]
