# Generated by Django 6.0.2 on 2026-09-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0033_remove_stagingznpsapexcel_init_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gozcontractvat',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Изделие'),
        ),
        migrations.AlterField(
            model_name='gozcontractvat',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Год'),
        ),
    ]
