# Generated by Django 6.0.2 on 2026-09-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0034_alter_gozcontractvat_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagingSumExcel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('igk', models.CharField(max_length=50, verbose_name='ИГК (имя листа)')),
                ('is_cycle', models.BooleanField(default=False, verbose_name='Длинноцикличный')),
                ('dep', models.CharField(max_length=50, null=True, verbose_name='ЦФО')),
                ('counteragent', models.TextField(null=True, verbose_name='Контрагент')),
                ('inn', models.TextField(null=True, verbose_name='ИНН')),
                ('contract', models.CharField(max_length=255, null=True, verbose_name='Договор')),
                ('status', models.CharField(max_length=255, null=True, verbose_name='Состояние')),
                ('stage', models.CharField(max_length=255, null=True, verbose_name='Этап')),
                ('item', models.TextField(null=True, verbose_name='Предмет')),
                ('order_doc', models.CharField(max_length=255, null=True, verbose_name='Заказ')),
                ('contract_sum', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('plan_avans', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('percent_doc', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('fact_paid', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('note', models.TextField(null=True)),
                ('completed_sum', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('znp_count', models.IntegerField(null=True)),
                ('sum_80', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('paid_from_znp', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('remains_pay', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('sum_avans', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('sum_issued_znp', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('period_reg_date', models.DateField(null=True)),
                ('plan_date_contract', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'Строка импорта Краткой справки',
                'verbose_name_plural': 'Строки импорта Краткой справки',
                'db_table': 'staging_sum_excel',
            },
        ),
    ]
