# Generated by Django 6.0.2 on 2026-10-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0035_stagingsumexcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagingznpsapexcel',
            name='created_date',
            field=models.DateField(null=True, verbose_name='Дата создания заявки'),
        ),
        migrations.AddField(
            model_name='znpdatasap',
            name='created_date',
            field=models.DateField(null=True, verbose_name='Дата создания заявки'),
        ),
    ]
