# Generated by Django 6.1.1 on 2026-10-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0037_stagingsumexcel_report_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StagingSumExcel',
        ),
        migrations.AlterField(
            model_name='contractcountssnapshot',
            name='cfo',
            field=models.CharField(max_length=50, verbose_name='ЦФО'),
        ),
        migrations.AlterField(
            model_name='contractcountssnapshot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contractcountssnapshot',
            name='year_col',
            field=models.CharField(max_length=5, verbose_name='Колонка года'),
        ),
        migrations.AlterField(
            model_name='contractsappeared',
            name='c_agent',
            field=models.CharField(max_length=255, null=True, verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='contractsappeared',
            name='cfo',
            field=models.CharField(max_length=50, null=True, verbose_name='ЦФО'),
        ),
        migrations.AlterField(
            model_name='contractsappeared',
            name='contract',
            field=models.CharField(max_length=255, null=True, verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='contractsappeared',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contractsappeared',
            name='igk',
            field=models.CharField(max_length=50, null=True, verbose_name='ИГК'),
        ),
        migrations.AlterField(
            model_name='contractsappeared',
            name='item',
            field=models.CharField(max_length=255, null=True, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='contractsappeared',
            name='order_num',
            field=models.CharField(max_length=100, null=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='contractsappeared',
            name='stage',
            field=models.CharField(max_length=250, null=True, verbose_name='Этап'),
        ),
        migrations.AlterField(
            model_name='contractsappeared',
            name='status',
            field=models.CharField(max_length=100, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='contractshistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contractshistory',
            name='new_status',
            field=models.CharField(max_length=100, null=True, verbose_name='Новый статус'),
        ),
        migrations.AlterField(
            model_name='contractshistory',
            name='old_status',
            field=models.CharField(max_length=100, null=True, verbose_name='Старый статус'),
        ),
        migrations.AlterField(
            model_name='igkstatdata',
            name='c_agent',
            field=models.CharField(max_length=255, null=True, verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='igkstatdata',
            name='c_date',
            field=models.CharField(max_length=50, null=True, verbose_name='Дата заключения'),
        ),
        migrations.AlterField(
            model_name='igkstatdata',
            name='cfo',
            field=models.CharField(max_length=50, null=True, verbose_name='ЦФО'),
        ),
        migrations.AlterField(
            model_name='igkstatdata',
            name='contract',
            field=models.CharField(max_length=255, null=True, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='igkstatdata',
            name='crc32_hash',
            field=models.BigIntegerField(verbose_name='CRC32 хеш'),
        ),
        migrations.AlterField(
            model_name='igkstatdata',
            name='igk',
            field=models.CharField(max_length=50, null=True, verbose_name='Код ИГК'),
        ),
        migrations.AlterField(
            model_name='igkstatdata',
            name='item',
            field=models.CharField(max_length=255, null=True, verbose_name='Предмет договора'),
        ),
        migrations.AlterField(
            model_name='igkstatdata',
            name='order',
            field=models.CharField(max_length=100, null=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='igkstatdata',
            name='payment_type',
            field=models.CharField(max_length=100, null=True, verbose_name='Тип платежа'),
        ),
        migrations.AlterField(
            model_name='igkstatdata',
            name='plan_date',
            field=models.CharField(max_length=50, null=True, verbose_name='Плановая дата'),
        ),
        migrations.AlterField(
            model_name='igkstatdata',
            name='pp_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='igkstatdata',
            name='status',
            field=models.CharField(max_length=100, null=True, verbose_name='Статус договора'),
        ),
        migrations.AlterField(
            model_name='nsiigk',
            name='igk_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_fired',
            field=models.BooleanField(default=False, verbose_name='Уволен'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sync_error',
            field=models.TextField(blank=True, verbose_name='Ошибка синхронизации'),
        ),
        migrations.AlterField(
            model_name='stagingexcel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stagingznpexcel',
            name='crc32_hash',
            field=models.BigIntegerField(verbose_name='CRC32 хеш'),
        ),
        migrations.AlterField(
            model_name='stagingznpexcel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stagingznpsapexcel',
            name='bank_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='stagingznpsapexcel',
            name='c_agent',
            field=models.CharField(max_length=255, null=True, verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='stagingznpsapexcel',
            name='c_type',
            field=models.CharField(max_length=50, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='stagingznpsapexcel',
            name='cfo',
            field=models.CharField(max_length=50, null=True, verbose_name='ЦФО'),
        ),
        migrations.AlterField(
            model_name='stagingznpsapexcel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stagingznpsapexcel',
            name='igk',
            field=models.CharField(max_length=50, null=True, verbose_name='ИГК'),
        ),
        migrations.AlterField(
            model_name='systemevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='znpdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='znpdata',
            name='znp_igk',
            field=models.CharField(max_length=50, null=True, verbose_name='ИГК заявки'),
        ),
        migrations.AlterField(
            model_name='znpdatasap',
            name='bank_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='znpdatasap',
            name='c_agent',
            field=models.CharField(max_length=255, null=True, verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='znpdatasap',
            name='cfo',
            field=models.CharField(max_length=50, null=True, verbose_name='ЦФО'),
        ),
        migrations.AlterField(
            model_name='znpdatasap',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='znpdatasap',
            name='igk',
            field=models.CharField(max_length=50, null=True, verbose_name='ИГК'),
        ),
    ]
